# Generated by Django 4.1.7 on 2023-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('user_id', models.BigIntegerField(verbose_name='User ID')),
                ('schema_id', models.BigIntegerField(verbose_name='Schema ID')),
                ('rows', models.IntegerField(verbose_name='Rows')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('file', models.FileField(upload_to='media/csv/')),
            ],
        ),
    ]
