# Generated by Django 4.1.7 on 2023-03-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='User ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='User Name')),
                ('title', models.CharField(max_length=255, verbose_name='Schema Title')),
                ('fields', models.JSONField(default=dict)),
                ('data_create', models.DateField(auto_now_add=True)),
                ('data_update', models.DateField(auto_now=True)),
            ],
        ),
    ]
