# Generated by Django 4.1.7 on 2023-03-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemas',
            name='character',
            field=models.CharField(blank=True, max_length=30, verbose_name='String Character'),
        ),
        migrations.AddField(
            model_name='schemas',
            name='separators',
            field=models.CharField(blank=True, max_length=30, verbose_name='Column Separator'),
        ),
    ]
